[input]
    read1 = 'input_read1.fq.gz'

[output]
    prefix = 'output'
    compression = 'Raw'


[[step]]
    action = 'Head'
    n = 10
[[step]]
    action = 'ExtractRegion'
    anchor = "Start"
	source = "read1"
    start = 0
    length = 4
    out_label = 'xyz'

[[step]]
    action = 'Demultiplex'
    in_label = 'xyz'
	barcodes = 'demult'
    output_unmatched = true

[barcodes.demult]
    GNAA = 'label1'
    CTNN = 'label2'
