[input]
    read1 = 'input_read1.fq'

[[step]]
    action = 'ExtractRegex'
    source = 'read1'
    out_label = 'test'
    search = '$'
    replacement = 'AGTC'

[[step]]
    action = 'StoreTagInSequence'
    in_label = 'test'

[output]
    prefix = 'output'
