# todo: rework barcodes so that 'empty barcode' is the collector, not a specially named output,
[input]
    read1 = 'sample_data/ERR664392_1250.fq.gz'

[output]
    prefix = 'output'
    compression = 'Raw'

[[step]]
    action = 'ExtractRegion'
    source = "read1"
	anchor = "Start"
    start = 0
    length = 2
    out_label = '12'

[[step]]
    action = 'Demultiplex'
    in_label = '12'
	barcodes = 'key'
    output_unmatched = false

[barcodes.key]
    CT = 'aaaa'
    TT = 'no-barcode'

