[input]
    read1 = 'input_read1.fq'

[[step]]
    action = 'Head'
    n = 4

[[step]]
    action = 'ExtractRegex'
    out_label = 'motif1'
    source = "read1"
    search = 'C(T.)C'
    replacement = '$1'

[[step]]
    action = 'ExtractRegions'
    out_label = 'motif2'
    regions = [{segment = 'read1', start = 5, length = 3, anchor="start"}]

[[step]]
    action = 'StoreTagsInTable'
    infix = 'tags'
	#format = 'JSON'
	compression = 'shu'

[output]
    prefix = 'output'
	format = 'None'
