[input]
    read1 = ['input_read1.fq.gz']

[input.options]
    format = 'rapidgzip'

[options]
    block_size = 10 # to test that Head is actually total
    thread_count = 4 # use multiple threads for rapidgzip

[[step]]
    action='Head'
    n = 5

[output]
    prefix = 'output'
