[input]
    read1 = 'input_read1.fq'

[[step]]
    action = 'TagDuplicates'
    out_label = 'is_duplicate'
    false_positive_rate = 0.0
    source = "read1"

[[step]]
    action = 'FilterByNumericTag'
    keep_or_remove = 'Keep'
    in_label = 'is_duplicate'
    min_value = 1.0

[output]
    prefix = 'output'
