[input]
    read1 = 'input_read1.fq.zst'
[options]
    block_size = 15

[[step]]
    action = '_InternalReadCount'
    out_label = 'top'

[[step]]
    action = 'Report'
    name = 'report_top'
    count = true

[[step]]
    action ='Head'
    n = 10

[[step]]
    action = '_InternalReadCount'
    out_label = 'middle'

[[step]]
    action ='Head'
    n = 1

[[step]]
    action = '_InternalReadCount'
    out_label = 'bottom'

[output]
    prefix = 'output'
    report_json = true
