[input]
    read1 = 'input_read1.fq'
    read2 = 'input_read2.fq'

[[step]]
    action = 'ExtractIUPAC'
    anchor = 'Anywhere'
    out_label = 'test'
    segment = 'read2'
    search = 'TCAA'
    max_mismatches = 0

[[step]]
    action = 'TrimAtTag'
    in_label = 'test'
    direction = 'End'
    keep_tag = false

[output]
    prefix = 'output'
