[input]
    read1 = 'input_read1.fq'
    read2 = 'input_read1.fq'

[input.options]
  accept_duplicate_files = true

  
[[step]]
    action = 'ValidateAllReadsSameLength'
    segment = 'all'
[output]
    prefix = 'output'
