[input]
    read1 = 'input_read1.fq'

[[step]]
    action = 'Head'
    n = 2

[[step]]
    action = 'ExtractRegions'
    out_label='umi'
    regions = [{segment = 'read1', start = 1, length = 5}]

[[step]]
    action = 'StoreTagInComment'
    in_label = 'umi'

[output]
    prefix = 'output'
