[input]
    read1 = 'input_read1.fq'

[[step]]
    action = 'ExtractPolyTail'
    out_label = 'a_label_with_underscores'
    min_length = 10
    base = 'A'
    max_mismatch_rate = 0.10
    max_consecutive_mismatches = 2

[[step]]
	action = 'TrimAtTag'
	in_label = 'a_label_with_underscores'
	direction = 'end'
	keep_tag = false

[output]
    prefix = 'output'
