[input]
    read1 = 'input_read1.fq.zst'
[options]
    block_size = 15 # number of reads per block. We keep it low, and should see much fewer than the 10k
                    # in teh input file,
                    # depending on the actual schedulding


[[step]]
    action = '_InternalReadCount'
    out_label = 'top'

[[step]]
    action ='Head'
    n = 10

[[step]]
    action = 'Report'
    name = 'report_middle'
    count = true


[[step]]
    action = '_InternalReadCount'
    out_label = 'middle'

[[step]]
    action ='Head'
    n = 1

[[step]]
    action = '_InternalReadCount'
    out_label = 'bottom'

[output]
    prefix = 'output'
    report_json = true
