[input]
    read1 = 'input_read1.fq'

[[step]]
    action = 'ExtractPolyTail'
	out_label = 'my___label'
    base = 'N'
    min_length=1
    max_mismatch_rate=0
    max_consecutive_mismatches=0

[[step]]
	action = 'TrimAtTag'
	direction = 'end'
    keep_tag = false
	in_label = 'my___label'

[[step]]
    action = 'ExtractIUPAC'
    out_label = 'test'
    anchor = 'Right'
    search = 'AAW'

[[step]]
    action = 'LowercaseTag'
    in_label = 'test'

[[step]]
    action = 'StoreTagInSequence'
    in_label = 'test'

[output]
    prefix = 'output'
