[input]
    read1 = 'sample_data/ten_reads.fq'

[[step]]
    action = 'EvalExpression'
	out_label = 'eval_result'
	expression = '5 * whatever'
	result_type = 'numeric'

[output]
    prefix = 'output'
