[input]
    read1 = 'input_read1.fq'

[[step]]
    action = 'ExtractIUPACSuffix'
	label = 'hit'
    query = 'GATCGGAAGAGCACACGTCTGAACTCCAGTCAC'
    min_length = 12
    max_mismatches = 0
[[step]]
	action = 'TrimAtTag'
	label = 'hit'
    direction = 'end'
    keep_tag = false

[output]
    prefix = 'output'
