[input]
    read1 = 'input_read1.fq'

[[step]]
    action = 'Head'
    n = 4

[[step]]
	action = "ExtractRegion"
	start = 0
	len = 4
	out_label = "my_tag"

[[step]]
    action = 'StoreTagInComment'
	in_label = "my_tag"
	comment_separator = 'A'

[output]
    prefix = 'output'
    format = 'None'
