[input]
    read1 = 'input_read1.fq'

[[step]]
    action = 'ExtractIUPAC'
    out_label = 'test'
    anchor = 'Left'
    search = 'CTN'
    max_mismatches = 0
[[step]]
    action = 'UppercaseTag'
    in_label = 'test'

[[step]]
    action = 'StoreTagInComment'
    in_label = 'test'

[output]
    prefix = 'output'
