[input]
    read1 = 'sample_data/ten_reads.fq'

[[step]]
    action = 'CalcBaseContent'
    out_label = 'g_content'
    bases_to_count = 'G'
    bases_to_ignore = 'N'
    relative = false

[output]
    prefix = 'output'
