[input]
    read1 = 'input_read1.fq'

[[step]]
  action = "ExtractRegion"
  out_label = "reg"
  start = 0
  anchor = 'Start'
  length = 3
  source = 'read1'


[[step]]
  out_label= 'cutme'
  action = 'EvalExpression'
  expr = 'read_no % 2 == 0'
  result_type = 'bool'

[[step]]
    if_tag = 'cutme'
    action = 'CutStart'
    n = 5


[[step]]
  action = 'StoreTagInComment'
  in_label = 'reg'

[[step]]
  action = 'StoreTagLocationInComment'
  in_label = 'reg'


[output]
    prefix = 'output'
