[input]
    read1 = 'sample_data/ten_reads_twice.fq'


[[step]]
    action = 'Report'
    name = 'xyz'
    count = false
    base_statistics = false
    duplicate_count_per_read = false
    duplicate_count_per_fragment = false
    length_distribution = false
    count_oligos = ['NA', 'TGG']
    count_oligos_segment = 'read1'

[output]
    prefix = 'output'
    report_json=true
