[input]
    read1 = 'input_read1.fq'

[[step]]
    action = 'ExtractRegionsOfLowQuality'
    out_label = 'low_quality'
    min_quality = 40
    min_length = 27

[[step]]
    action = 'StoreTagLocationInComment'
    in_label = 'low_quality'

[output]
    prefix = 'output'
