[input]
    read1 = ["test_cases/input/basic/1kread.fq"]

[[step]]
    action = 'Report'
    name = 'test'
    base_statistics = true
    counting_strategy = "merged"

[output]
    prefix = 'test_output'
    report_json = true
