[input]
    read1 = 'input_read1.fq.zst'
    options.read_comment_character = ' '

[[step]]
    action = 'TagOtherFile'
    source = 'name:read1'
	out_label = 'tag'
    filename = 'input_ERR12828869_10k_1.head_500.bam'
    include_mapped = true
    include_unmapped = false
    false_positive_rate = 0.0001
    seed  = 42
    other_readname_end_char = ' '

[[step]]
	action = "FilterByTag"
	in_label = "tag"
    keep_or_remove = 'Remove'

[output]
    prefix = 'output'
	compression = 'zst'
