[input]
    read1 = 'input_read1.fq'
    read2 = 'input_read2.fq'

[[step]]
    action = 'ExtractIUPAC'
    out_label = 'test'
    anchor = 'Left'
    search = 'CTN'
    segment = 'index1'

[[step]]
    action = 'ExtractIUPAC'
    out_label = 'test2'
    anchor = 'Left'
    search = 'CTN'
    segment = 'index2'

[output]
    prefix = 'output'
