[input]
read1 = "../../../../test_cases/sample_data/fastp_606.fq.gz"
read2 = "../../../../test_cases/sample_data/fastp_606.fq.gz"

[options]
    thread_count = 4
    block_size=10000
    accept_duplicate_files = true

[benchmark]
    enable = true
    molecule_count = 100_000_000

[[step]]
    action = "MergeReads"
    min_overlap = 10
    algorithm = "Fastp"
    max_mismatch_rate=0.2
    no_overlap_strategy="as_is"
    reverse_complement_segment2 = true
    segment1 = "read1"
    segment2 = "read2"
