[input]
    read1 = 'input_read1.fq'



[[step]]
    action = 'CalcNCount'
	out_label = 'nn'

[[step]]
	action ='FilterByNumericTag'
	max_value = 26
	in_label = 'nn'
	keep_or_remove = 'keep'


[output]
    prefix = 'output'
