[input]
    read1 = 'input_read1.fq'

[[step]]
    action = 'ExtractLongestPolyX'
	out_label="mytag"
	base ='A'
    min_length=3
    max_mismatch_rate=0
    max_consecutive_mismatches=0


[[step]]
    action = 'ConvertRegionsToLength'
    out_label = 'region_len'
    in_label = 'mytag'

[[step]]
    action = 'StoreTagInComment'
    in_label = 'region_len'
    segment = 'read1'

[output]
    prefix = 'output'
