[input]
    read1 = 'input_read1.fq'

[[step]]
    action = 'Head'
    n = 3
[[step]]
    action = 'ExtractIUPAC'
    out_label='tg'
    search = 'TG'
    anchor = 'Anywhere'
[[step]]
    action = 'TrimAtTag'
    in_label = 'tg'
    direction = 'End'
    keep_tag = false

[[step]]
    action = 'CalcGCContent'
    out_label = 'gc_content'

[[step]]
    action = 'StoreTagInComment'
    in_label = 'gc_content'

[output]
    prefix = 'output'
