[input]
    read1 = 'input_read1.fq.gz'

[output]
    prefix = 'output'

[[step]]
    action = 'Head'
    n = 10

[[step]]
    action = 'ExtractRegion'
    anchor = "Start"
	source = "read1"
    start = 0
    length = 2
    out_label = 'xyz'

[[step]]
    action = 'Demultiplex'
    in_label = 'xyz'
	barcodes = 'demult'
    output_unmatched = false

[barcodes.demult]
    CT = 'aaaa'
    TT = 'gggg'
