[input]
    read1 = 'input_read1.fq'
    read2 = 'input_read2.fq'
    index1 = 'input_i1.fq'
    index2 = 'input_i2.fq'

[[step]]
    action = 'ExtractIUPAC'
    out_label = 'test'
    anchor = 'Right'
    search = 'CTN'
    segment = 'index1'
    max_mismatches = 0

[[step]]
    action = 'StoreTagInComment'
    in_label = 'test'
	segment = 'read1'

[[step]]
    action = 'StoreTagInComment'
    in_label = 'test'
	segment = 'read2'

[[step]]
    action = 'StoreTagInComment'
    in_label = 'test'
	segment = 'index1'

[[step]]
    action = 'StoreTagInComment'
    in_label = 'test'
	segment = 'index2'


[output]
    prefix = 'output'
    output = []
