[input]
    read1 = 'input_read1.fq'



[[step]]
    action = 'ExtractRegex'
	search = "AGTT"
	label = 'regexp_one'
	source = 'read1'

[[step]]
    action = 'ExtractRegex'
	search = "GATC"
	label = 'regex_two'
	source = 'read1'

[[step]]
	action = 'EvalExpression'
	label = 'both'
	expression = '''
		regexp_one and regex_two
	'''
    result_type = 'bool'

[[step]]
	action ='FilterByTag'
	label = 'both'
	keep_or_remove = 'keep'


[output]
    prefix = 'output'