[input]
    read1 = 'input_read1.fq'


[[step]]
    action = 'CalcLength'
    segment = 'read1'
    out_label = 'length'

[[step]]
    action = 'StoreTagInComment'
    in_label = 'length'
    segment = 'read1'

[output]
    prefix = 'output'
