[input]
    read1 = 'sample_data/ten_reads.fq'

[[step]]
    action = 'ExtractIUPAC'
    out_label = 'barcode'
    search = 'CTN'
    anchor = 'Left'

[[step]]
    action = 'CalcLength'
    segment = 'read1'
    out_label = 'length_tag'

[[step]]
    action = 'ForgetAllTags'

[[step]]
    action = 'StoreTagInComment'
    in_label = 'barcode'

[output]
    prefix = 'output'
