[input]
    read1 = 'input_read1.fq'

[[step]]
    action = 'CalcExpectedError'
    out_label = 'expected_error'
    aggregate = 'sum'

[[step]]
    action = 'StoreTagInComment'
    in_label = 'expected_error'

[output]
    prefix = 'output'
