[input]
    read1 = 'input_read1.bam'
	options.bam_include_mapped = true
	options.bam_include_unmapped = true


[[step]]
    action = 'Report'
    name = 'xyz'
    count = true
    base_statistics = true
    duplicate_count_per_read = true
    length_distribution = true

[output]
    prefix = 'output'
    report_json=true
