[input]
read1 = "input_read1.fq"

[output]
compression = "zst"
prefix = "output"

[[step]]
action = "TagOtherFileByName"
false_positive_rate = -0.000001
filename = "other_read1.fq"
out_label = "tag"
seed = 42

[[step]]
action = "FilterByTag"
in_label = "tag"
keep_or_remove = "Remove"
