[input]
    read1 = 'input_read1.fq.zst'
    read2 = 'input_read2.fq.zst'

[options]
  max_blocks_in_flight = 1

[[step]]
    action = 'Report'
    name = 'xyz'
    duplicate_count_per_read = true
    length_distribution = true
    base_statistics = true

[output]
    prefix = 'output'
    report_json = true
	format = 'None'


