[input]
    read1 = 'input_read1.fq'

[[step]]
    action = 'CalcNCount'
    segment = 'read1'
    label = 'n_count'

[[step]]
    action = 'CalcLength'
    segment = 'read1'
    label = 'length'

[[step]]
    action = 'EvalExpression'
    label = 'log_e_rate'
    expression = 'log(e(), n_count + 1) - log(e(), length + 1)'
    result_type= "numeric"

[[step]]
    action = 'EvalExpression'
    label = 'log2_rate'
    expression = 'log(2, n_count) - log(2, length)'
    result_type= "numeric"

[[step]]
    action = 'EvalExpression'
    label = 'log10_rate'
    expression = 'log(10, n_count) - log(10, length)'
    result_type= "numeric"

[[step]]
    action = 'StoreTagInComment'
    label = 'log_e_rate'
    segment = 'read1'

[[step]]
    action = 'StoreTagInComment'
    label = 'log2_rate'
    segment = 'read1'

[[step]]
    action = 'StoreTagInComment'
    label = 'log10_rate'
    segment = 'read1'

[output]
    prefix = 'output'
