[input]
    read1 = 'sample_data/ten_reads.fq'

[[step]]
    action = 'ExtractIUPAC'
    out_label = 'something'
    search = 'CTN'
    anchor ='Left'

[[step]]
    action = 'ExtractIUPAC'
    out_label = 'other'
    search = 'CTN'
    anchor ='Left'

[[step]]
    action = 'FilterByTag'
    keep_or_remove = 'Keep'
    in_label = 'test'

[output]
    prefix = 'output'
