[input]
    read1 = 'test_cases/integration_tests/quality_base_replacement/input_read1.fq.gz'

[[step]]
    action = 'ExtractRegionsOfLowQuality'
    segment = 'read1'
    min_quality = 60
    out_label = 'low_quality'

[output]
    prefix = 'output'
    compression = 'raw'
