[input]
	read1 = 'input_uncompressed.fq'

[[step]]
	action = "CalcLength"
	segment = "read1"
	out_label = "read1_length"
[[step]]
	action = "FilterByNumericTag"
	in_label = "read1_length"
	min_value = 5000
	keep_or_remove = 'keep'


[output]
	prefix = 'output'
	compression = 'gz'
