[input]
	read1 = 'input_read1.fq'
[[step]]
	action = 'Head'
	n = 2
[[step]]
	action = 'ExtractIUPAC'
	out_label = 'tag'
	search = 'TCA'
	anchor = 'Anywhere'
[[step]]
    action ='Prefix'
	seq = 'AGT'
	qual = "ABC"
[[step]]
	action='StoreTagLocationInComment'
	in_label = 'tag'

[[step]]
	action='LowercaseTag'
	in_label = 'tag'

[[step]]
	action = 'StoreTagInSequence'
	in_label ='tag'

[output]
	prefix = 'output'
