[input]
    read1 = 'input_read1.fq'
    read2 = 'input_read2.fq'

[[step]]
    action = 'ExtractIUPAC'
    out_label = 'test'
    anchor = 'Anywhere'
    search = 'CTN'
    segment = 'read2'

[[step]]
    action = 'StoreTagInComment'
    in_label = 'test'
	segment = 'read2'

[output]
    prefix = 'output'
