[input]
    read1 = 'input_read1.fq'

[[step]]
    action = 'ExtractPolyTail'
	out_label = 'pt'
    min_length = 10
    base = '.'
    max_mismatch_rate = 0.09
    max_consecutive_mismatches = 3
[[step]]
	action = "TrimAtTag"
	in_label = "pt"
	direction = "end"
	keep_tag = false


[[step]]
    action = 'CalcLength'
	out_label = 'el'

[[step]]
	action = "FilterByNumericTag"
	in_label ="el"
	max_value = 14
	keep_or_remove =   'remove'


[output]
    prefix = 'output'
