[input]
    read1 = 'sample_data/ten_reads.fq'

[[step]]
    action = 'ExtractIUPAC'
    out_label = 'real_tag'
    search = 'CTN'
    anchor ='Left'

[[step]]
    action = 'ForgetTag'
    in_label = 'nonexistent_tag'

[output]
    prefix = 'output'
