[input]
    read1 = 'input_read1.fq.zst'

[[step]]
    action = 'TagOtherFileByName'
    filename = 'input_ERR12828869_10k_1.head_500.bam'
	out_label = "tag"
    include_mapped = false
    include_unmapped = true
    false_positive_rate = 0
    seed  = 42
    fastq_readname_end_char = ' '
    reference_readname_end_char = ' '

[[step]]
	action = "FilterByTag"
	in_label = "tag"
    keep_or_remove = 'Remove'


[output]
    prefix = 'output'
	compression = 'zst'
