[input]
    read1 = 'input_read1.fq.gz'


[[step]]
    action = 'Head'
    n = 2

[[step]]
    action = 'ExtractRegions'
    out_label = 'UMI'
    regions = [{segment = 'read1', start = 200, length = 6, anchor="Start"},
               {segment = 'read1', start = 250, length = 6, anchor="Start"}]

[[step]]
    action = 'StoreTagInComment'
    in_label = 'UMI'

[output]
    prefix = 'output'
