[input]
    # Single-end reads for this example
    # For paired-end data, you would also include: read2 = 'input/sample_R2.fq'
    read1 = 'input/sample_R1.fq'

[[step]]
  action = "CalcGCContent"
  out_label = "gc_content"

[[step]]
    # Generate a comprehensive quality report
    action = 'Report'
    name = 'initial'

    # Count total number of reads
    count = true

    # Analyze base quality scores and GC content
    base_statistics = true
    # Analyze the distribution of read lengths

    length_distribution = true

    # Count duplicate reads (identical sequences)
    duplicate_count_per_read = true

    # Count duplicate reads (identical sequences)
    duplicate_count_per_fragment = true

    # count how often these oligos occur.
    # no mismatches, no IUPAC
	count_oligos = [
		'AAAAAA',
		'GATCGGAAGAGCACACGTCTGAACTCCAGTCAC',
		'ATCTCGTATGCCGTCTTCTGCTTG',
		'GGGGGGGGGGG',
	]

    # Histogram of gc content (rounded to nearest integer)
  # optional
    tag_histograms = ["gc_content"]


[output]
    # Output prefix for all files
    prefix = 'reference_output/output'

    # Generate both HTML and JSON reports
    report_html = true
    report_json = true

    # Output format (FASTQ = uncompressed FASTQ format)
    format = "FASTQ"
