[input]
    read1 = 'input_read1.fasta'
	options.fasta_fake_quality = 33


[[step]]
    action = 'Report'
    name = 'xyz'
    count = true
    base_statistics = true
    duplicate_count_per_read = true
    length_distribution = true

[output]
    prefix = 'output'
    report_json=true
