[input]
    read1 = 'input_read1.fq'

[[step]]
    action = 'Head'
    n = 4

[[step]]
    action = 'ExtractRegions'
    out_label='umi'
    regions = [
        {segment = 'read1', start = 0, length = 51, anchor="Start"},
    ]

[[step]]
    action = 'LowercaseTag'
    in_label = 'umi'

[[step]]
    action = 'StoreTagInComment'
	region_separator = '-'
    in_label = 'umi'

[output]
    prefix = 'output'
