[input]
    read1 = 'input_read1.fq'

[[step]]
    action = 'Head'
    n = 4

[[step]]
	action = "ExtractRegion"
    anchor = "Left"
	source = "read1"
	start = 0
	len = 4
	out_label = "my,tag"

[[step]]
    action = 'StoreTagInComment'
	in_label = "my,tag"
	comment_separator = ','

[output]
    prefix = 'output'
    format = 'None'
