[input]
    read1 = 'input_read1.fq.gz'

[output]
    prefix = 'output'
    compression = 'Raw'
	format = 'FASTQ'


[[step]]
    action = 'Head'
    n = 10

[[step]]
    action = 'ExtractRegion'
    start = 0
    length = 4
    out_label = 'xyz'

# Since we're using inline barcodes, we can't use HammingCorrect with shared barcodes yet
# For now, just remove hamming distance and do exact matching
[[step]]
    action = 'Demultiplex'
    in_label = 'xyz'
    output_unmatched = true
	barcodes = 'demult'

[barcodes.demult]
    ATGA = 'label1'
    CTCC = 'label2'
