[input]
	read1 = 'input_read1.fq'
[[step]]
	action = 'Head'
	n = 2
[[step]]
	action = 'ExtractIUPAC'
	out_label = 'tag'
	search = 'TCA'
	anchor = 'Anywhere'
	max_mismatches = 0
[[step]]
    action ='ReverseComplement'
[[step]]
	action='StoreTagLocationInComment'
	in_label = 'tag'

[[step]]
	action='Lowercase'
	source = 'tag:tag'

[[step]]
	action = 'StoreTagInSequence'
	in_label ='tag'

[output]
	prefix = 'output'
