[input]
    read1 = 'sample_data/ten_reads.fq'

[[step]]
    action = 'CalcGCContent'
    out_label = 'gc_content'

[[step]]
    action = 'FilterByTag'
    keep_or_remove = 'Keep'
    in_label = 'gc_content'

[output]
    prefix = 'output'
