[input]
    read1 = 'sample_data/ten_reads.fq'
[[step]]
    action = 'ExtractIUPACSuffix'
	out_label = "label"
    query = 'agctc'
    min_length = 6
    max_mismatches = 3

[output]
    prefix = 'output'
