[input]
    read1 = 'input_read1.fq'
    read2 = 'input_read2.fq'

[[step]]
    action = 'ExtractIUPAC'
    anchor = 'Anywhere'
    out_label = 'test'
    segment = 'read2'
    search = 'TCAA'
    max_mismatches = 0

[[step]]
    action = 'ExtractIUPAC'
    anchor = 'Anywhere'
    out_label = 'check1'
    segment = 'read1'
    search = 'TCA'
    max_mismatches = 0

[[step]]
    action = 'ExtractIUPAC'
    anchor = 'Anywhere'
    out_label = 'check2'
    segment = 'read2'
    search = 'GGA'
    max_mismatches = 0


[[step]]
    action = 'TrimAtTag'
    in_label = 'test'
    direction = 'End'
    keep_tag = true

[[step]]
	action = 'StoreTagInComment'
	in_label = 'check1'
	segment = 'All'

[[step]]
	action = 'StoreTagLocationInComment'
	in_label = 'check1'
	segment = 'All'

[[step]]
	action = 'StoreTagInComment'
	in_label = 'check2'
	segment = 'All'

[[step]]
	action = 'StoreTagLocationInComment'
	in_label = 'check2'
	segment = 'All'

[[step]]
	action = 'StoreTagInComment'
	in_label = 'test'
	segment = 'All'

[[step]]
	action = 'StoreTagLocationInComment'
	in_label = 'test'
	segment = 'All'




[[step]]
	action = 'LowercaseTag'
	in_label = 'check1'

[[step]]
	action = 'LowercaseTag'
	in_label = 'check2'

[[step]]
	action = 'StoreTagInSequence'
	in_label = 'check1'
	ignore_missing=true

[[step]]
	action = 'StoreTagInSequence'
	in_label = 'check2'
	ignore_missing=true

[output]
    prefix = 'output'
