[input]
    read1 = 'input_read1.fq.gz'

[output]
    prefix = 'output'

[[step]]
    action = 'ExtractRegion'
    anchor = "Start"
    source = 'read1'
    start = 0
    length = 2
    out_label = 'a12'

[[step]]
	action = "StoreTagInComment"
	in_label = 'a12'

[[step]]
    action = 'Demultiplex'
    in_label = 'a12'
	barcodes='bc123'

    output_unmatched = true

[barcodes.bc123]
    CT = 'ct'
    TT = 'tt'

[[step]]
    action = 'ExtractRegion'
    anchor = "Start"
    source = 'read1'
    start = 4
    length = 2
    out_label = 'b46'

[[step]]
	action = "StoreTagInComment"
	in_label = 'b46'

[[step]]
    action = 'Demultiplex'
    in_label = 'b46'
	barcodes='bc46'

    output_unmatched = true

[barcodes.bc46]
    AG = 'ag'
    AT = 'at'


