[input]
    read1 = 'input_read1.fq.gz'

[[step]]
    action = 'ExtractRegions'
    regions = [
            { source = 'read1', start = 6, length = 6, anchor='start'}
    ]
    out_label = 'regs'

[[step]]
    action = 'QuantifyTag'
    infix = 'kmer'
    in_label = 'regs'

[output]
    prefix = 'output'
	format = 'None'
