[input]
    read1 = 'input_read1.fq.gz'

[output]
    prefix = 'output'


[[step]]
    action = 'Head'
    n = 10

[[step]]
    action = 'ExtractRegion'
    anchor = "Start"
	source = "read1"
    start = 0
    length = 4
    out_label = 'xyz'

[[step]]
	action ='HammingCorrect'
	in_label = 'xyz'
	out_label = 'abc'
	max_hamming_distance = 1
	barcodes = 'demult'
	on_no_match = 'keep'


[[step]]
    action = 'Demultiplex'
    in_label = 'abc'
	barcodes = 'demult'
    output_unmatched = true

[barcodes.demult]
    GNAA = 'label1'
    CTNN = 'label2'
