[input]
    read1 = 'sample_data/ERR664392_1250.fq.gz'
[[step]]
    action = 'ExtractRegions'
    out_label = ''
    regions = [{source = 'read1', start = 0, length = 6, anchor="left"}]


[output]
  prefix = 'out'
