[input]
    read1 = 'input_read1.fq.zst'

[[step]]
    action = 'TagOtherFileBySequence'
	out_label = 'tag'
    filename = 'input_ERR12828869_250_aligned_250_unaligned.bam'
    include_mapped = false
    include_unmapped = false
    false_positive_rate = 0
    seed  = 42

[[step]]
	action = "FilterByTag"
	in_label = "tag"
    keep_or_remove = 'Remove'


[output]
    prefix = 'output'
	compression = 'zst'
