[input]
    read1 = 'input_read1.fq.zst'
    read2 = 'input_read2.fq.zst'


[[step]]
    action = 'TagDuplicates'
    false_positive_rate = 0.0
    source = 'read1'
	out_label = 'a24'

[[step]]
	action = 'FilterByTag'
	in_label = 'a24'
    keep_or_remove='remove'

[output]
    prefix = 'output'
	compression = 'zstd'
