[input]
    read1 = 'input_read1.fq'

[output]
    prefix = 'output'

[[step]]
    action = 'TagOtherFile'
    source = "name:read1"
    out_label = 'in_other_file'
    filename = 'input_other_file.fq'
    false_positive_rate = 0
    seed = 42

[[step]]
    action = 'Demultiplex'
    in_label = 'in_other_file'
    output_unmatched = false
