[input]
    read1 = 'input_read1.fq'


[[step]]
    action = 'CalcQualifiedBases'
	label = 'qb'
    threshold='C'
	op = '>='

[[step]]
	action = 'CalcLength'
	segment = 'read1'
	label = 'length'

[[step]]
	action = 'EvalExpression'
	label = 'qbr'
	expression = 'qb / length'
	result_type= 'numeric'

# [[step]]
# 	action = 'StoreTagsInTable'
# 	table_filename = 'debug'

[[step]]
	action = "FilterByNumericTag"
	label = 'qbr'
    min_value = 0.37
	keep_or_remove = 'keep'


[output]
    prefix = 'output'
