[input]
	read1 = 'input_read1.fq'

[[step]]
	action = 'ExtractIUPAC'
	out_label = 'tag'
	search = 'TCA'
	anchor = 'Anywhere'
	max_mismatches = 0
[[step]]
	action = 'ExtractIUPAC'
	out_label = 'tag_before'
	search = 'TCA'
	anchor = 'Anywhere'
	max_mismatches = 0
[[step]]
	action='StoreTagLocationInComment'
	in_label = 'tag_before'

[[step]]
    action ='CutStart'
    n = 5
[[step]]
	action='StoreTagLocationInComment'
	in_label = 'tag'

[[step]]
	action='Lowercase'
	source = 'tag:tag'

[output]
	prefix = 'output'
