[input]
    read1 = [
		'input_data.fq.zst', 'input_data.fq.zst', 'input_data.fq.zst', 'input_data.fq.zst',
		'input_data.fq.zst', 'input_data.fq.zst', 'input_data.fq.zst', 'input_data.fq.zst',
		'input_data.fq.zst', 'input_data.fq.zst', 'input_data.fq.zst', 'input_data.fq.zst',
		'input_data.fq.zst', 'input_data.fq.zst', 'input_data.fq.zst', 'input_data.fq.zst',
		'input_data.fq.zst', 'input_data.fq.zst', 'input_data.fq.zst', 'input_data.fq.zst',
		'input_data.fq.zst', 'input_data.fq.zst', 'input_data.fq.zst', 'input_data.fq.zst',

	]

[options]
	block_size = 1000
    accept_duplicate_files = true
	threads = 1


# [[step]]
#   action = 'Progress'

[output]
    prefix = 'output_double'
    format = 'fastq'
