[input]
    read1 = 'input_read1.fq.zst'

[input.options]
read_comment_character = ' '

[[step]]
    action = 'TagOtherFile'
    source = 'name:read1'

	out_label = 'tag'
    filename = 'input_ERR12828869_250_aligned_250_unaligned.bam'
    include_mapped = true
    include_unmapped = false
    false_positive_rate = 0
    seed  = 42
    # fastq_readname_end_char = ' '
    other_readname_end_char = ' '

[[step]]
	action = "FilterByTag"
	in_label = "tag"
    keep_or_remove = 'Remove'

[output]
    prefix = 'output'
	compression = 'zst'
