[input]
    read1 = 'input_read1.fq.gz'


[[step]]
    action = 'Head'
    n = 2

[[step]]
    action = 'ExtractRegions'
    out_label = 'UMI'
    regions = [{segment = 'read1', start = 0, length = 6}]

[[step]]
    action = 'TrimAtTag'
    in_label = 'UMI'
    direction = 'Start'
    keep_tag = false

[[step]]
    action = 'StoreTagInComment'
    in_label = 'UMI'
    comment_separator = ' '
	comment_insert_char = '!'

[output]
    prefix = 'output'
