[input]
    read1 = 'input_read1.fq'

[[step]]
    action = 'ExtractRegex'
    out_label = 'test'
    source = 'read1'
    search = 'N{2,}'
    replacement = '$0'

[[step]]
    action = 'LowercaseTag'
    in_label = 'test'

[[step]]
    action = 'StoreTagInSequence'
    in_label = 'test'

[output]
    prefix = 'output'
