[input]
    read1 = 'input_read1.fq'

[[step]]
    action = 'Head'
    n = 2

[[step]]
    action = 'CalcLength'
    out_label = 'total_length'
    segment='all'

[[step]]
    action = 'CalcLength'
    out_label = 'read1_length'
[[step]]
	action = "StoreTagInComment"
	in_label = "total_length"

[[step]]
	action = "StoreTagInComment"
	in_label = "read1_length"

[output]
    prefix = 'output'
    output = ["read1"]
