[input]
    read1 = 'input_read1.fq'
options.read_comment_character = '/'

[[step]]
    action = 'TagOtherFile'
    out_label = 'present'
    segment = 'name:read1'
    filename = 'input_reference.fq'
    false_positive_rate = 0
    seed = 42
    other_readname_end_char = ' '

[[step]]
    action = 'FilterByTag'
    in_label = 'present'
    keep_or_remove = 'Keep'

[output]
    prefix = 'output'
    compression = 'raw'
