[input]
    read1 = 'input_read1.fq'

[[step]]
    action = 'Head'
    n = 2

[[step]]
    action = 'CalcBaseContent'
    out_label = 'at_content'
    bases_to_count = 'AT'
    bases_to_ignore = 'N'

[[step]]
    action = 'CalcBaseContent'
    out_label = 'at_no_g'
    bases_to_count = 'AT'
    bases_to_ignore = 'NG'

[[step]]
    action = 'StoreTagInComment'
    in_label = 'at_content'

[[step]]
    action = 'StoreTagInComment'
    in_label = 'at_no_g'

[output]
    prefix = 'output'
