[input]
    read1 = 'input_read1.fq'

[[step]]
    action = 'Head'
    n = 2

[[step]]
    action = 'CalcGCContent'
    out_label = 'total_gc'
[[step]]
    action = 'CalcGCContent'
    out_label = 'read1_gc'
[[step]]
	action = "StoreTagInComment"
	in_label = "total_gc"

[[step]]
	action = "StoreTagInComment"
	in_label = "read1_gc"

[output]
    prefix = 'output'
    output = ["read1"]
