[input]
    read1 = 'input_read1.fq'

[[step]]
	action = "ExtractRegion"
    anchor = "Left"
	source = "read1"
	start = 0
	len = 4
	out_label = "len_read1"

[output]
    prefix = 'output'
    format = 'None'
