[input]
    read1 = 'input_read1.fq'

[[step]]
    action = 'TagOtherFileByName'
    out_label = 'present'
    segment = 'read1'
    filename = 'input_reference.fq'
    false_positive_rate = 0
    seed = 42
    fastq_readname_end_char = '/'
    reference_readname_end_char = ' '

[[step]]
    action = 'FilterByTag'
    in_label = 'present'
    keep_or_remove = 'Keep'

[output]
    prefix = 'output'
    compression = 'raw'
