[input]
	read1 = 'input_read1.fq'


[[step]]
	action = 'ExtractIUPAC'
	out_label = 'tag'
	search = 'TCA'
	anchor = 'Anywhere'
	max_mismatches = 0

[[step]]
	action = 'ExtractIUPAC'
	out_label = 'tag_before'
	search = 'TCA'
	anchor = 'Anywhere'
	max_mismatches = 0
[[step]]
	action='StoreTagLocationInComment'
	in_label = 'tag_before'


[[step]]
    action = 'ExtractLowQualityStart'
	out_label = 'lowq'
    min_qual = 'C'

[[step]]
	action='TrimAtTag'
	in_label = 'lowq'
	direction = 'start'
	keep_tag = false

[[step]]
	action='StoreTagLocationInComment'
	in_label = 'tag'

[[step]]
	action='LowercaseTag'
	in_label = 'tag'

[[step]]
	action = 'StoreTagInSequence'
	in_label ='tag'
	ignore_missing=true

[output]
	prefix = 'output'
