[input]
    read1 = 'input_read1.fq'

[[step]]
    action = 'ExtractRegex'
    out_label = 'test'
    search = 'N{2,}'
    replacement = ''
    source = "read1"

[[step]]
    action = 'StoreTagInSequence'
    in_label = 'test'

[output]
    prefix = 'output'
