[input]
    read1 = 'input_read1.fq'

[[step]]
    action = 'ExtractRegex'
    out_label = 'barcode'
    segment = 'read1'
#search = ':([A-Z]+):'
	search = "TA."

[[step]]
    action = 'FilterByTag'
    in_label = 'barcode'
    keep_or_remove = 'Keep'

[[step]]
    action = 'StoreTagInComment'
    in_label = 'barcode'

[output]
    prefix = 'output'
