[input]
    read1 = 'input_read1.fq'

[[step]]
    action = 'ExtractIUPAC'
    out_label = 'test'
    search = 'CTN'
    anchor ='Left'
    max_mismatches = 0

[[step]]
    action = 'FilterByTag'
    keep_or_remove = 'Remove'
    in_label = 'test'

[output]
    prefix = 'output'
