[input]
	read1 = 'input_read1.fq'

[[step]]
	action = 'ExtractIUPAC'
	out_label = 'tag'
	search = 'TCA'
	anchor = 'Anywhere'
[[step]]
	action = 'ExtractIUPAC'
	out_label = 'tag_before'
	search = 'TCA'
	anchor = 'Anywhere'
[[step]]
	action='StoreTagLocationInComment'
	in_label = 'tag_before'
[[step]]
   action ='CutEnd'
   n = 45
[[step]]
	action='StoreTagLocationInComment'
	in_label = 'tag'

[[step]]
	action='LowercaseTag'
	in_label = 'tag'

[[step]]
	action = 'StoreTagInSequence'
	in_label ='tag'
	ignore_missing = true

[output]
	prefix = 'output'
