[input]
    read1 = 'input_read1.fq'

[[step]]
    action = 'CalcNCount'
    segment = 'read1'
    out_label = 'n_count'

[[step]]
    action = 'CalcLength'
    segment = 'read1'
    out_label = 'length'

[[step]]
    action = 'EvalExpression'
    out_label = 'high_n_rate'
    expression = '(n_count / length) > 0.5'
    result_type = 'bool'

[[step]]
    action = 'StoreTagInComment'
    in_label = 'high_n_rate'
    segment = 'read1'

[output]
    prefix = 'output'
