[input]
    read1 = 'input_read1.fq.zst'


[[step]]
	action = "ExtractRegex"
	search = "^ERR12828869[.]1.*[^ ]+"
	source = 'name:read1'
	out_label = 'input'

[[step]]
    action = 'TagDuplicates'
    false_positive_rate = 0.0
    source = 'tag:input'
	out_label = '_24'

[[step]]
	action = 'FilterByTag'
	in_label = '_24'
    keep_or_remove='remove'

[output]
    prefix = 'output'
	compression = 'zstd'
