[input]
    read1 = 'input_read1.fq.gz'

[output]
    prefix = 'output'

[[step]]
    action = 'Head'
    n = 10

[[step]]
    action = 'ExtractRegion'
	source = "read1"
    anchor = "Start"
    start = 0
    length = 2
    out_label = 'xyz'


[[step]]
	action = 'HammingCorrect'
	out_label = 'xyz_corrected'
	in_label = 'xyz'
	barcodes = 'mine'
	max_hamming_distance = 1
	on_no_match = 'Keep'

[[step]]
    action = 'Demultiplex'
    in_label = 'xyz_corrected'
    output_unmatched = true
	barcodes = 'mine'

[barcodes.mine]
    CT = 'aaaa'
