[input]
    read1 = 'input_read1.fq'

[[step]]
    action = 'ExtractIUPAC'
    out_label = 'mytagname'
    anchor = 'Left'
    search = 'ATCG'
    max_mismatches = 0

[[step]]
    action = 'StoreTagInFastQ'
    in_label = 'mytagname'
    compression = 'Gzip'
    compression_level = 6

[output]
    prefix = 'output'
	output = []
	ix_separator = '.'
