# We used to 'shut down' the input when a head was 'full',
# but we must not do that if a Report/Quantify/Inspect was before

[input]
    read1 = 'input_read1.fq.zst'
    read2 = 'input_read2.fq.zst'
[options]
    block_size = 15

[[step]]
    action ='Head'
    n = 10

[[step]]
    action = 'ExtractRegions'
    out_label = 'kmer'

    regions = [
            { segment = 'read1', anchor="Start", start = 6, length = 6},
    ]
[[step]]
    action = 'QuantifyTag'
    infix = 'kmer'
    in_label = 'kmer'

[output]
    prefix = 'output'


