[input]
    read1 = 'input_read1.fq.zst'

[[step]]
    action = 'TagOtherFile'
    source = 'name:read1'
	out_label = "tag"
    filename = 'input_no_reads.fq.gz'
    false_positive_rate = 0.000001 # so we trigger the other code path
    seed  = 42

[[step]]
	action = "FilterByTag"
	in_label = "tag"
    keep_or_remove = 'Remove'


[output]
    prefix = 'output'
	compression = 'zst'
