[input]
    read1 = 'input_read1.fq'



[[step]]
    action = 'ExtractRegex'
	search = "\\d\\d"
	out_label = 'regexp_one'
	source = 'name:read1'


[[step]]
	action = 'EvalExpression'
	out_label = 'both'
	expression = '''
		regexp_one
	'''
    result_type = 'bool'

[[step]]
	action ='FilterByTag'
	in_label = 'both'
	keep_or_remove = 'keep'


[output]
    prefix = 'output'
