[input]
    read1 = 'input_read1.fq'
    read2 = 'input_read2.fq'

[[step]]
    action = 'CalcNCount'
    segment = 'All'
    out_label = 'n_count'

[[step]]
    action = 'CalcLength'
    segment = 'All'
    out_label = 'total_length'

[[step]]
    action = 'EvalExpression'
    out_label = 'n_per_base_all'
    expression = 'n_count / total_length'
    result_type= "numeric"

[[step]]
    action = 'StoreTagInComment'
    in_label = 'n_per_base_all'
    segment = 'read1'

[output]
    prefix = 'output'
