[input]
    read1 = 'input_read1.fq'

[[step]]
    action = 'Progress'
    n = 1
    output_infix = 'progress'


[[step]]
    action = 'TagOtherFileByName'
    filename = 'input_tag_source.fq'
    out_label = 'present'
    false_positive_rate = 0.0


[[step]]
    action = 'TagOtherFileBySequence'
    filename = 'input_tag_source.fq'
    out_label = 'present_seq'
    false_positive_rate = 0.0


[[step]]
    action = 'StoreTagInComment'
    in_label = 'present'
    segment = 'read1'

[[step]]
    action = 'StoreTagInComment'
    in_label = 'present_seq'
    segment = 'read1'


[output]
    prefix = 'output'
    format = 'none'
    output = ['read1']
