[input]
	read1 = 'input_read1.fq'

 [[step]]
	action = 'ExtractRegionsOfLowQuality'
	out_label = 'elq'
	min_quality = 'J'
	min_length = 1

[[step]]
	action= 'StoreTagLocationInComment'
	in_label = 'elq'

[[step]]
	action= 'TrimAtTag'
	in_label = 'elq'
	direction = 'Start'
	keep_tag = false


[output]
	prefix = 'output'
