[input]
    read1 = 'read1.fq'
    read2 = 'read2.fq'

[[step]]
    action = 'MergeReads'
    reverse_complement_segment2 = true
    segment1 = 'read1'
    segment2 = 'read2'
    algorithm = 'Fastp'
    min_overlap = 5
    max_mismatch_rate = 1.0
    max_mismatch_count = 0
    no_overlap_strategy = 'as_is'

[output]
    prefix = 'output'
