[input]
    read1 = 'input_read1.fq'

[[step]]
    action = 'ExtractRegex'
    out_label = 'barcode'
    segment = 'name:read1'
    search = 'read(\d+)'
    replacement = '$0-$1'


[[step]]
	action = 'TrimAtTag'
	in_label = 'barcode'
	direction = 'start'
	keep_tag=false

[[step]]
	action = 'StoreTagInComment'
	in_label = 'barcode'

[output]
    prefix = 'output'
