[input]
    read1 = 'input_read1.fq'
    read2 = 'input_read2.fq'
    index1 = 'input_index1.fq'
    index2 = 'input_index2.fq'

[options]
    accept_duplicate_files = true

[[step]]
	action = 'ValidateName'
	read_name_end_char = 'd'


[[step]]
    action = 'Head'
    n = 2

[[step]]
    action = 'ExtractRegions'
    out_label = 'UMI'
    regions = [{segment = 'read1', start = 1, length = 5, anchor="Start"}]

[[step]]
    action = 'StoreTagInComment'
    in_label = 'UMI'
    segment = 'All'

[output]
    prefix = 'output'
    output = ["read1", "read2", "index1", "index2"]
