[input]
    index1 = 'input_index1.fq'
    read1 = 'input_read1.fq'
    read2 = 'input_read2.fq'
    index2 = 'input_index2.fq'

[options]
    accept_duplicate_files = true

[[step]]
    action = 'ExtractLength'
	label = 'ðŸ––'
    target = 'Index1'
[[step]]
	action = 'FilterByNumericTag'
	max_value = 4
	keep_or_remove = 'keep'
	label = 'ðŸ––'


[output]
    prefix = 'output'
