[input]
read1 = "input_read1.fq"

[output]
compression = "zst"
prefix = "output"

[[step]]
action = "TagOtherFile"
source = 'read1'
false_positive_rate = 1.0
filename = "other.fq"
out_label = "tag"
seed = 42

[[step]]
action = "FilterByTag"
in_label = "tag"
keep_or_remove = "Remove"
