[input]
    read1 = 'input_read1.fq'

[[step]]
    action = 'ExtractIUPAC'
    search = "CAYA"
    out_label = 'anchor_tag'
    anchor = 'Anywhere'
    max_mismatches = 0

[[step]]
    action = 'ExtractRegions'
    regions = [
        { source = "tag:anchor_tag", start = -2, length = 4, anchor = "Start" },
        { source = "tag:anchor_tag", start = -100, length = 10, anchor = "Start" }
    ]
    out_label = 'test'

[[step]]
    action = 'FilterByTag'
	in_label = 'test'
    keep_or_remove = 'Keep'

[[step]]
    action = 'StoreTagLocationInComment'
	in_label = 'test'

[[step]]
    action = 'StoreTagInComment'
	in_label = 'test'

[output]
    prefix = 'output'
