[input]
    read1 = 'sample_data/ten_reads.fq'

[[step]]
    action = 'ExtractIUPAC'
    out_label = 'test'
    search = 'CTN'
    anchor = 'Left'
    max_mismatches = 0

[[step]]
    action = 'ExtractIUPAC'
    out_label = 'test'
    anchor = 'Left'
    search = 'GCN'
    max_mismatches = 0

[output]
  prefix = 'out'
