[input]
    read1 = 'input_read1.fq'
[[step]]
    action = 'ExtractRegex'
	search = "A+"
    out_label = 'read_length'
	source = 'read1'

[[step]]
    action = 'ValidateAllReadsSameLength'
    source = 'tag:read_length'

[output]
    prefix = 'output'
