[input]
    read1 = 'sample_data/ten_reads.fq'
[[step]]
    action = 'ExtractIUPACSuffix'
	out_label = "..."
    query = 'agctc'
    min_length = 5
    max_mismatches = 6

[output]
    prefix = 'output'
