[input]
    read1 = 'sample_data/ten_reads_of_var_sizes.fq'

[[step]]
    action = 'Report'
    name = 'report'

[[step]]
    action = 'Report'
    name = 'report'

[output]
    prefix = 'output'
    report_json = true

