[input]
    read1 = 'input_read1.fq'

[[step]]
    action = 'Head'
    n = 2

[[step]]
    action = 'CalcLength'
    out_label = 'length'

[[step]]
    action = 'StoreTagInComment'
    in_label = 'length'

[output]
    prefix = 'output'
