[input]
    read1 = 'input_read1.fq'
    read2 = 'input_read2.fq'
    index1 = 'input_index1.fq'
    index2 = 'input_index2.fq'

[[step]]
    action = 'CalcNCount'
    out_label = 'total_n'
    segment = 'All'

[[step]]
    action = 'CalcNCount'
    out_label = 'read1_n'
    segment = 'read1'

[[step]]
    action = 'CalcNCount'
    out_label = 'read2_n'
    segment = 'read2'

[[step]]
    action = 'CalcNCount'
    out_label = 'index1_n'
    segment = 'index1'

[[step]]
    action = 'CalcNCount'
    out_label = 'index2_n'
    segment = 'index2'

[[step]]
    action = 'StoreTagInComment'
    in_label = 'total_n'

[[step]]
    action = 'StoreTagInComment'
    in_label = 'read1_n'
[[step]]
    action = 'StoreTagInComment'
    in_label = 'read2_n'
[[step]]
    action = 'StoreTagInComment'
    in_label = 'index1_n'
[[step]]
    action = 'StoreTagInComment'
    in_label = 'index2_n'

[output]
    prefix = 'output'
    output = ["read1"]
