[input]
    read1 = 'input_r1.fq'

[output]
    prefix = 'output'

[[step]]
    action = 'ExtractRegion'
    start = 0
    length = 4
    out_label = 'barcode'

[[step]]
    action = 'Demultiplex'
    in_label = 'barcode'
    barcodes = 'test_barcodes'
    output_unmatched = false

[barcodes.test_barcodes]
    'ATCG' = 'specific'
    'ATCR' = 'specific'
