[input]
    read1 = 'input_read1.fq'

[[step]]
    action = 'ExtractPolyTail'
	out_label = 'pt'
    min_length = 10
    base = 'G'
    max_mismatch_rate = 0.11
    max_consecutive_mismatches = 3

[[step]]
	action = "TrimAtTag"
	in_label = "pt"
	direction = "end"
	keep_tag = false


[[step]]
    action = 'CalcLength'
	out_label = 'el'
[[step]]
	action = 'FilterByNumericTag'
	in_label ='el'
	min_value =  14
	keep_or_remove = 'Keep'



[output]
    prefix = 'output'
