[input]
    read1 = 'input_read1.fq.zst'

[[step]]
    action = 'TagOtherFileBySequence'
	label = 'tag'
    filename = 'input_ERR12828869_10k_1.head_500.all_unaligned.bam'
    ignore_unaligned = true
    false_positive_rate = 0
    seed  = 42
	# this is essentially a no op. See the _no_ignore test case for actual removal

[[step]]
	action = "FilterByTag"
	label = "tag"
    keep_or_remove = 'Remove'



[output]
    prefix = 'output'
	compression = 'zst'