[input]
    read1 = 'input_read1.fq'

[[step]]
    action = 'ExtractIUPAC'
    out_label='tg'
    search = 'TG'
    anchor = 'Anywhere'

[[step]]
    action = 'TrimAtTag'
    in_label = 'tg'
    direction = 'Start'
    keep_tag = false

[[step]]
    action = 'CalcNCount'
    out_label = 'n_count'

[[step]]
    action = 'StoreTagInComment'
    in_label = 'n_count'

[output]
    prefix = 'output'
