[input]
read1 = "../../../../test_cases/sample_data/fastp_606.fq.gz"
#  read1 = "../../../../test_cases/sample_data/filter/input_read1_1.fq"

[options]
    thread_count = 4
    block_size=10000
    accept_duplicate_files = true

[benchmark]
    enable = true
    molecule_count = 100_000_000

[[step]]
    action = "Prefix"
    segment = "read1"
    seq = "A"
    qual = "I"
  

