[input]
    read1 = 'input_read1.fq.gz'

[output]
    prefix = 'output'
    compression = 'Raw'


[[step]]
    action = 'Head'
    n = 10
[[step]]
    action = 'ExtractRegions'
	regions = [
		{ start = 0, length = 2, anchor="Start", source="read1"},
		{ start = 2, length = 2, anchor="Start", source="read1"},
	]
    out_label = 'xyz'

[[step]]
	action = "StoreTagInComment"
	in_label = "xyz"

[[step]]
    action = 'Demultiplex'
    in_label = 'xyz'
	barcodes = 'demult'

    output_unmatched = true

[barcodes.demult]
    GN_AA = 'label1'
    CT_NN = 'label2'
