[input]
    read1 = 'input_read1.fq'

[[step]]
    action = 'ExtractIUPAC'
    search = "CACA"
    max_mismatches = 1
    out_label = 'anchor_tag'
    anchor = 'Anywhere'

[[step]]
    action = 'ExtractRegions'
    regions = [
		{ source = "tag:anchor_tag", start=0, length=4, anchor='left'},
		{ source = "tag:anchor_tag", start=4, length=4, anchor='left'},
	]
    out_label = 'test'


[[step]]
    action = 'FilterByTag'
    in_label = 'test'
    keep_or_remove = 'Keep'

[[step]]
    action = 'StoreTagLocationInComment'
    in_label = 'test'

[[step]]
    action = 'StoreTagInComment'
    in_label = 'test'
	region_separator = 'X'

[output]
    prefix = 'output'
