[input]
    read1 = 'input_read1.fq'
    read2 = 'input_read2.fq'
    index1 = 'input_index1.fq'
    index2 = 'input_index2.fq'

[[step]]
    action = 'Head'
    n = 2

[[step]]
    action = 'CalcGCContent'
    out_label = 'total_gc'
    segment = 'All'

[[step]]
    action = 'CalcGCContent'
    out_label = 'read1_gc'
    segment = 'read1'

[[step]]
    action = 'CalcGCContent'
    out_label = 'read2_gc'
    segment = 'read2'

[[step]]
    action = 'CalcGCContent'
    out_label = 'index1_gc'
    segment = 'index1'

[[step]]
    action = 'CalcGCContent'
    out_label = 'index2_gc'
    segment = 'index2'

[[step]]
    action = 'StoreTagInComment'
    in_label = 'total_gc'

[[step]]
    action = 'StoreTagInComment'
    in_label = 'read1_gc'
[[step]]
    action = 'StoreTagInComment'
    in_label = 'read2_gc'
[[step]]
    action = 'StoreTagInComment'
    in_label = 'index1_gc'
[[step]]
    action = 'StoreTagInComment'
    in_label = 'index2_gc'

[output]
    prefix = 'output'
    output = ["read1"]
