[input]
    read1 = 'input_read1.fq'
    read2 = 'input_read2.fq'

[[step]]
    action = 'MergeReads'
    algorithm = 'Fastp'
    min_overlap = 10
    max_mismatch_rate = 0.2
    no_overlap_strategy = 'as_is'
    reverse_complement_segment2 = true
    segment1 = 'read1'
    segment2 = 'read2'

[output]
    prefix = 'output'
