[input]
    read1 = 'input_read1.fq'


[[step]]
    action = 'CalcGCContent'
    out_label = 'gc_content'

[[step]]
    action = 'StoreTagInSequence'
    in_label = 'gc_content'

[output]
    prefix = 'output'
