[input]
    read1 = 'input_read1.fq'

[[step]]
    action = 'ExtractRegion'
    out_label = 'barcode'
    source = "name:read1"
    anchor = "left"
    length = 3
    start = 1


[[step]]
	action = 'StoreTagLocationInComment'
	in_label = 'barcode'
     segment = "read1" # Any of your input segments, or 'All'
     comment_insert_char = ' ' # (optional) char at which to insert comments
     comment_separator = '|' # (optional) char to separate comments

[[step]]
	action = 'StoreTagInComment'
	in_label = 'barcode'


[output]
    prefix = 'output'
