[input]
    read1 = 'input_read1.fq'

[[step]]
    action = 'ExtractIUPAC'
    search = "AAAA"
    out_label = 'barcode1'
    anchor = 'Left'
    max_mismatches = 0

[[step]]
    action = 'ExtractRegex'
    search = "."
    out_label = 'barcode2'
	source = "name:read1"

[[step]]
    action = 'ConcatTags'
    in_labels = ['barcode1', 'barcode2']
    out_label = 'combined'
    on_missing = 'merge_present'

[[step]]
    action = 'StoreTagInComment'
    in_label = 'combined'

[[step]]
    action = 'StoreTagLocationInComment'
    in_label = 'combined'


[output]
    prefix = 'output'
