[input]
    read1 = 'input_read1.fq'

[[step]]
    action = 'ExtractIUPAC'
    out_label = 'barcode'
    anchor = 'Left'
    search = 'ATCG'

[[step]]
    action = 'ExtractRegions'
    out_label = 'umi'
    regions = [{segment = 'read1', start = 4, length = 4}]

[[step]]
    action = 'StoreTagInFastQ'
    in_label = 'barcode'
    comment_tags = ['umi']
    comment_separator = '|'
    comment_insert_char = ' '

[output]
    prefix = 'output'
