[input]
    read1 = 'input_read1.fq'

[[step]]
    action = 'Head'
    n = 2

[[step]]
    action = 'CalcNCount'
    out_label = 'total_n'
[[step]]
    action = 'CalcNCount'
    out_label = 'read1_n'
[[step]]
	action = "StoreTagInComment"
	in_label = "total_n"

[[step]]
	action = "StoreTagInComment"
	in_label = "read1_n"

[output]
    prefix = 'output'
    output = ["read1"]
