#baseURL = 'https://tyberiusprime@github.io/pypipegraph2'
#canonifyURLs = true
languageCode = 'en-us'
title = 'mbf-fastq-processor documentation'
theme = "hugo-book"

[params]
  BookRepo = 'https://github.com/TyberiusPrime/mbf-fastq-processor'
