[input]
    read1 = 'input_read1.fq'
    options.read_comment_character = ' '

[[step]]
  action = "CalcLength"
  segment = "read1"
  out_label="len"

[[step]]
  action = "StoreTagInComment"
  in_label="len"
  comment_separator = '!'


[[step]]
    action = 'TagOtherFile'
    segment = 'name:read1'
    out_label = 'present'
    filename = 'input_reference.fq'
    false_positive_rate = 0
    seed = 42
    other_readname_end_char = ' '

[[step]]
    action = 'FilterByTag'
    in_label = 'present'
    keep_or_remove = 'Keep'

[output]
    prefix = 'output'
    compression = 'raw'
