[input]
    read1 = ['input_read1.bam', 'input_read1_2.bam']
	options.bam_include_unmapped=true
	options.bam_include_mapped=true

[[step]]
  action = "Head"
  n = 5

[output]
    prefix = 'output'
    format = 'fastq'
