[input]
    read1 = 'input_read1.fq.gz'

[output]
    prefix = 'output'

[[step]]
    action = 'ExtractRegion'
    start = 0
    length = 3 # and just like that, no barcode *can* match.
    label = 'an12'

[[step]]
	action = "StoreTagInComment"
	label = 'an12'

[[step]]
    action = 'Demultiplex'
    label = 'an12'
	barcodes='B123'

    output_unmatched = true

[barcodes.B123]
    CT = 'ct'
    TT = 'tt'

