[input]
    read1 = 'input_read1.fq'

[output]
    prefix = 'output'

[[step]]
    action = 'QuantifyKmers'
    label = 'kmer_count'
    segment = 'read1'
    files = ['input_kmers.fa']
    k = 4
    min_count = 1

[[step]]
    action = 'FilterByNumericTag'
    label = 'kmer_count'
    min_value = 1
    keep_or_remove = 'keep'
