[input]
    read1 = 'input_read1.fq'

[[step]]
    action = 'Head'
    n = 4

[[step]]
    action = 'ExtractIUPAC'
    out_label = 'barcode1'
    search = 'CTC'
    anchor = 'Left'

[[step]]
    action = 'ExtractIUPAC'
    out_label = 'barcode2'
    search = 'CAA'
    anchor = 'Anywhere'

[[step]]
    action = 'StoreTagsInTable'
    infix = 'tags'
	compression = 'gz'
	#format = 'TSV'

[output]
    prefix = 'output'
	format = 'None'
