[input]
    read1 = 'input_read1.fq'
    read2 = 'input_read2.fq'

[[step]]
    action = 'ExtractRegex'
    out_label = 'sample'
    segment = 'name:read1'
    search = 'sample_([0-9]+)'
    replacement = '$1'

[[step]]
    action = 'ExtractRegex'
    out_label = 'motif'
    segment = 'read2'
    search = 'GC(TT)AG'
    replacement = '$1'

[[step]]
    action = 'StoreTagInComment'
    in_label = 'sample'

[[step]]
    action = 'StoreTagInComment'
    in_label = 'motif'

[output]
    prefix = 'output'
