[input]
    read1 = 'input_read1.fq.zst'


[[step]]
    action = 'TagDuplicates'
    false_positive_rate = 0.0
    source = 'name:read1'
	label = 'a24'

[[step]]
	action = 'FilterByBoolTag'
	label = 'a24'
    keep_or_remove='remove'

[output]
    prefix = 'output'
	compression = 'zstd'
