[input]
    read1 = 'input_read1.fq'

[output]
    prefix = 'output'

[[step]]
    action = 'CalcKmers'
    out_label = 'kmer_count'
    segment = 'read1'
    files = 'input_kmers.fa'
    k = 4
    min_count = 2
    canonical = false

[[step]]
    action = 'StoreTagInComment'
    in_label = 'kmer_count'
