[input]
    read1 = 'input_read1.fq'

[[step]]
    action = 'Head'
    n = 2

[[step]]
    action = 'CalcGCContent'
    out_label = 'gc_content'
[[step]]
    action = 'StoreTagInComment'
    in_label = 'gc_content'

[output]
    prefix = 'output'
