name: Test Workflow
env:
  # The project name specified in your Cargo.toml
  PROJECT_NAME: mbf_fastq_processor
  GITHUB_ACTIONS: true

on:
  push:

jobs:
  checks:
    # permissions:
    #   contents: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false

      - name: Install Nix
        uses: cachix/install-nix-action@ba0dd844c9180cbf77aa72a116d6fbc515d0e87b # v27
      - name: Test
        run: nix build -L .#test


