[input]
    read1 = 'input_read1.fq.zst'
    read2 = 'input_read2.fq.zst'

[[step]]
    action = 'ExtractRegions'
    regions = [
            { segment = 'read1', start = 6, length = 6},
            { segment = 'read2', start = 10, length = 7}
    ]
    out_label = 'regs'


[[step]]
    action = 'QuantifyTag'
    infix = 'kmer'
    in_label = 'regs'
    region_separator = 'xyz'

[output]
    prefix = 'output'
	compression = 'Zst'
