[input]
    read1 = 'input_read1.fq'

[[step]]
    action = 'ExtractRegex'
    out_label = 'name:barcode'
    segment = 'read1'
    search = 'ACGT'
    replacement = '$1'

[output]
    prefix = 'output'
